freebsd_instance:
  image: freebsd-12-1-release-amd64

task:
  install_script:
    - sudo pkg install -y p5-App-cpanminus
    - sudo cpanm -v Alien::proj
    - sudo cpanm --installdeps --notest Alien::gdal

  script:
    - perl Makefile.PL
    - sudo cpanm --installdeps .
    - make
    - make test
