language: perl
perl:
  - "5.24"
#  - "5.22"

os:
  - linux
  - osx

sudo: false

cache:
  directories:
    - perl_modules

before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
  #  local::lib target is cached
  - cpanm --notest local::lib
  - eval "$(perl -Mlocal::lib=${PWD}/perl_modules)"

install:
  - cpanm --quiet Alien::Build
  - cpanm --quiet HTML::LinkExtor
