language: perl
perl:
#  - "5.24"
#  - "5.22"

os:
  #- linux
  - osx

sudo: required 

cache:
  directories:
    - perl_modules
    - /usr/local
before_install:
  - /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  - brew install perl
  - brew install cpanminus  
  #  make sure we get the brewed perl and cpanm etc
  - export PATH=/usr/local/bin:${PATH}
  #  local::lib target is cached
  - /usr/local/bin/cpanm --notest local::lib
  - eval "$(perl -Mlocal::lib=${PWD}/perl_modules)"
  - /usr/local/bin/cpanm --version
install:
  - /usr/local/bin/cpanm --quiet Alien::Build
  - /usr/local/bin/cpanm --quiet HTML::LinkExtor
