language: perl
perl:
  - "5.24"
#  - "5.22"

cache:
  directories:
    - perl_modules

before_install:
  #  local::lib target is cached
  - cpanm --notest local::lib
  - eval "$(perl -Mlocal::lib=${PWD}/perl_modules)"

install:
  - cpanm --quiet Alien::Build
  - cpanm --quiet HTML::LinkExtor
