language: perl
perl:
  - "5.26"
#  - "5.22"

os:
  - linux
  - osx

sudo: required 

cache:
  directories:
    - perl_modules
    - /usr/local

#env:
#  MAKEFLAGS='-j$(nproc)' - nope - exhausts memory

before_install:
    # Skip build if the commit message contains [skip travis] or [travis skip]
    #  (from https://github.com/htgoebel/pyinstaller/blob/develop/.travis.yml)
  - >
      echo "$TRAVIS_COMMIT_MESSAGE"
      | grep -E  '\[(skip travis|travis skip)\]'
      && echo "[skip travis] has been found, exiting."
      && exit 0 || true
# - if [ "$TRAVIS_OS_NAME" == "osx" ]; then /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"; fi;
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install perl; fi;
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install cpanminus; fi;

#  make sure we get the brewed perl and cpanm etc
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export PATH=/usr/local/bin:${PATH}; fi;
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then /usr/local/bin/cpanm --version; fi;

#  local::lib target is cached
  - cpanm --notest local::lib
  - eval "$(perl -Mlocal::lib=${PWD}/perl_modules)"

# Add to PATH to find gdal-config
  #- if [ "$TRAVIS_OS_NAME" == "linux" ]; then export PATH=${PWD}/blib/lib/auto/share/dist/Alien-gdal/bin:${PATH}; fi;

  #- cpanm --quiet Alien::Build
  #- cpanm --quiet HTML::LinkExtor
  #- cpanm --quiet Test::CChecker
  # just a small one to see if any cpanm call will help
  - cpanm File::BOM  

script:
  - echo "Running script"
  - perl Makefile.PL
  - make
  - make test
  #  minor debug
  - perl -Iblib/lib -Iblib/arch -MAlien::gdal -E 'say $ENV{PATH}'
