language: perl
perl:
  - "5.26"
#  - "5.22"

os:
  - linux
  - osx


sudo: required 

branches:
  except:
  - /appveyor/
  - /appveyor_ppm/

cache:
  directories:
    - ${HOME}/perl_modules
    - /usr/local
    - ${HOME}/.alienbuild/plugin_fetch_cache


#env:
#  MAKEFLAGS='-j$(nproc)' - nope - exhausts memory

before_install:
    # Skip build if the commit message contains [skip travis] or [travis skip]
    #  (from https://github.com/htgoebel/pyinstaller/blob/develop/.travis.yml)
  - >
      echo "$TRAVIS_COMMIT_MESSAGE"
      | grep -E  '\[(skip travis|travis skip)\]'
      && echo "[skip travis] has been found, exiting."
      && exit 0 || true

  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew ls --versions perl > /dev/null || brew install perl; fi;
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew outdated perl || brew upgrade perl; fi;
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew ls --versions cpanminus > /dev/null || brew install cpanminus; fi;
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew outdated cpanminus || brew upgrade cpanminus; fi;

#  make sure we get the brewed perl and cpanm etc
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export PATH=/usr/local/bin:${PATH}; fi;
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then /usr/local/bin/cpanm --version; fi;
  
  #  local::lib target is cached
  - cpanm --notest local::lib
  - echo $(perl -Mlocal::lib=${HOME}/perl_modules)
  - eval "$(perl -Mlocal::lib=${HOME}/perl_modules)"
  #- cpanm --local-lib=~/perl_modules local::lib && eval $(perl -I ~/perl_modules/lib/perl5/ -Mlocal::lib)
  
  - cpanm --quiet --notest Alien::Build 
  #  Alien::Build::MM sometimes goes missing
  - cpanm --quiet --notest Alien::Build::MM

  - cpanm --quiet --notest Sort::Versions
  - cpanm --quiet --notest PkgConfig
  - cpanm --quiet --notest Alien::Build::Plugin::Cleanse::BuildDir
  - cpanm --quiet --notest File::Find::Rule
  - cpanm --quiet --notest Alien::Build::Plugin::Fetch::Cache

  #  this is on cpan now
  #- cpanm --notest -v https://github.com/shawnlaffan/perl-alien-geos.git
  - cpanm -v --notest --installdeps Alien::geos::af
  - MAKEFLAGS=-j4 cpanm -v --notest Alien::geos::af
  #- cpanm -v --notest Alien::spatialite
  - MAKEFLAGS=-j4 cpanm -v --notest Alien::sqlite
  - ALIEN_INSTALL_TYPE=share cpanm -v Alien::libtiff
  #- cpanm -v --notest --installdeps Alien::proj
  - MAKEFLAGS=-j4 cpanm -v --notest Alien::proj~1.07
  #- perl -MAlien::proj -e1 || MAKEFLAGS=-j4 cpanm -v https://github.com/shawnlaffan/perl-alien-proj.git

  - cpanm --quiet --notest FFI::Platypus
  #  TESTING - should set up as a matrix option so we get both
  #  for this run, make sure it does not apply to Alien::geos::af
  #  so it will be a system install
  #- if [ "$TRAVIS_OS_NAME" == "osx" ]; then export ALIEN_INSTALL_TYPE=share; fi;

  - export quiet='--quiet'
  - cpanm ${quiet} --notest --installdeps .
  

script:
  #- export AUTOMATED_TESTING=1  #  for debug
  - export ALIEN_BUILD_PRELOAD=Fetch::Cache
  - perl Makefile.PL
  #- make | perl -ne 'BEGIN {$|=1; open our $log, ">", "build.log"}; print "\n" if 0 == ($. % 90); print "."; print {$log} $_;' || cat build.log
  - MAKEFLAGS=-j4 make
  #- tail -200 build.log
  #- make
  - make test TEST_VERBOSE=1
  #  minor debug
  #- perl -Mblib -MAlien::gdal -E 'say $ENV{PATH}'
  #  disable for now - osx builds hit issues
  #- [ "$TRAVIS_OS_NAME" != "osx" ] && cat blib/lib/auto/share/dist/Alien-gdal/lib/pkgconfig/gdal.pc
