language: perl
perl:
#  - "5.24"
#  - "5.22"

os:
  - linux
  - osx

sudo: required 

cache:
  directories:
    - perl_modules
    - /usr/local
before_install:
# - if [ "$TRAVIS_OS_NAME" == "osx" ]; then /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"; fi;
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install perl; fi;
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install cpanminus; fi;

#  make sure we get the brewed perl and cpanm etc
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export PATH=/usr/local/bin:${PATH}; fi;
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then /usr/local/bin/cpanm --version; fi;

#  local::lib target is cached
  - cpanm --notest local::lib
  - eval "$(perl -Mlocal::lib=${PWD}/perl_modules)"
  - find ${PERLBREW_ROOT} -nane gdal-config

install:
  - cpanm --quiet Alien::Build
  - cpanm --quiet HTML::LinkExtor
  - cpanm --quiet Test::CChecker
