branches:
  except:
    - /travis/
skip_tags: true

cache:
  - C:\strawberry

install:
  - if not exist "C:\strawberry" choco install strawberryperl --version 5.26.1.1
  - set ST=C:\strawberry
  - set PATH=%ST%\perl\bin;%ST%\perl\site\bin;%ST%\c\bin;%PATH%
  - cd C:\projects\%APPVEYOR_PROJECT_NAME%
  #  ensure we have some packages that aren't picked up by the install system
  - cpanm --quiet --notest Alien::Build
  - cpanm --quiet --notest Alien::patch
  - cpanm --quiet --notest HTML::LinkExtor
  - cpanm --quiet --notest Test::CChecker
  - cpanm --quiet --notest Alien::MSYS
  - gcc -v

build_script:
  - perl Makefile.PL
  - gmake | perl -ne "BEGIN {$|=1; open our $log, q|>|, q|build.log|}; print qq|\n| if 100 == ($. %% 100); print q|.|; print {$log} $_;" || type build.log
  - gmake test


