branches:
  except:
    - /travis/
skip_tags: true

cache:
  - C:\strawberry

install:
  - if not exist "C:\strawberry" choco install strawberryperl --version 5.26.1.1
  - set ST=C:\strawberry
  - set PATH=%ST%\perl\bin;%ST%\perl\site\bin;%ST%\c\bin;%PATH%
  - cd C:\projects\%APPVEYOR_PROJECT_NAME%
  #  ensure we have some packages that aren't picked up by the install system
  - cpanm --quiet Alien::Build
  - cpanm --quiet HTML::LinkExtor
  - cpanm --quiet Test::CChecker
  - cpanm --quiet Alien::MSYS
  - gcc -v

build_script:
  - perl Makefile.PL
  - gmake
  - gmake test


