---
abstract: 'Alien package for the Geospatial Data Abstraction Library (GDAL)'
author:
  - 'Shawn Laffan <shawnlaffan@gmail.com>'
build_requires:
  Alien::Build: '1.41'
  Alien::Build::MM: '1.41'
  Alien::MSYS: '0.07'
  Alien::patch: '0.09'
  Archive::Tar: '0'
  ExtUtils::MakeMaker: '6.52'
  File::Find::Rule: '0'
  HTML::LinkExtor: '0'
  HTTP::Tiny: '0.044'
  IO::Zlib: '0'
  PkgConfig: '0.19026'
  Sort::Versions: '0'
  Test::CChecker: '0'
  URI: '0'
  URI::Escape: '0'
  parent: '0'
configure_requires:
  Alien::Build: '1.41'
  Alien::Build::MM: '1.41'
  Alien::MSYS: '0'
  Alien::patch: '0'
  ExtUtils::MakeMaker: '6.52'
  File::Find::Rule: '0'
  HTTP::Tiny: '0.044'
  PkgConfig: '0'
  parent: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.3, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Alien-gdal
no_index:
  directory:
    - t
    - inc
requires:
  Alien::Base: '0.038'
  Alien::Build: '0.25'
resources:
  bugtracker: https://github.com/shawnlaffan/perl-alien-gdal/issues/
  repository: https://github.com/shawnlaffan/perl-alien-gdal
version: 1.06_001
x_alienfile:
  generated_by: 'Alien::Build::MM version 1.41'
  requires:
    share:
      Alien::MSYS: '0.07'
      Alien::patch: '0.09'
      Archive::Tar: '0'
      HTML::LinkExtor: '0'
      HTTP::Tiny: '0.044'
      IO::Zlib: '0'
      Sort::Versions: '0'
      URI: '0'
      URI::Escape: '0'
    system: {}
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
