name: linux_de_locale

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

env:
  PERL_MOD_DIR: /home/runner/perl5/lib/perl5

jobs:
  perl:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.32'

      - name: Locale check
        run: |
          locale -a
          sudo locale-gen de_DE
          sudo update-locale de_DE

      - name: Locale check 2
        run: |
          locale -a
          echo Current locale:
          locale

      - name: perl -V
        run: perl -V

      - name: Prepare for cache
        run: |
          perl -V > perlversion.txt
          echo '20210911' >> perlversion.txt
          ls -l perlversion.txt

      - name: Cache CPAN modules
        uses: actions/cache@v1
        with:
          path: ~/perl5
          key: ${{ runner.os }}-build-${{ hashFiles('perlversion.txt') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ hashFiles('perlversion.txt') }}

      - name: Install Dynamic Dependencies
        run: |
          which -a cpanm
          which -a perl
          cpanm --notest local::lib
          echo $(perl -Mlocal::lib=${HOME}/perl5)
          eval "$(perl -Mlocal::lib=${HOME}/perl5)"
          cpanm --notest Alien::Build  
          cpanm --installdeps --notest Alien::sqlite
          cpanm -v Alien::sqlite
          cpanm --installdeps --notest Alien::libtiff
          cpanm -v Alien::libtiff
          cpanm --installdeps --notest Alien::geos::af
          cpanm -v Alien::geos::af
          cpanm --installdeps --notest Alien::proj
          cpanm -v Alien::proj
          cpanm --installdeps --notest Alien::gdal
          
      - name: Run Tests
        run: |
          echo $(perl -Mlocal::lib=${HOME}/perl5)
          eval "$(perl -Mlocal::lib=${HOME}/perl5)"
          sudo update-locale de_DE
          export LC_NUMERIC=de_DE.iso88591
          export LC_CTYPE=de_DE.iso88591
          locale
          perl -MPOSIX -E'say join " ", POSIX::strtod 3.14'
          perl Makefile.PL
          cpanm --installdeps .
          make
          make test
