name: macos

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

env:
  PERL5LIB: /Users/runner/perl5/lib/perl5
  PERL_LOCAL_LIB_ROOT: /Users/runner/perl5
  PERL_MB_OPT: --install_base /Users/runner/perl5
  PERL_MM_OPT: INSTALL_BASE=/Users/runner/perl5

jobs:
  perl:

    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Perl
        run: |
          brew install perl
          echo "{/Users/runner/perl5/bin}" >> $GITHUB_PATH
          mkdir -p ~/bin
          cd ~/bin
          curl -L https://cpanmin.us/ -o cpanm
          chmod +x cpanm
          echo "{~/bin}" >> $GITHUB_PATH
          which perl
          which cpanm

      - name: Install GDAL and its deps
        run: brew install gdal
        
      - name: perl -V
        run: perl -V

      - name: Prepare for cache
        run: |
          perl -V > perlversion.txt
          echo '20201120' >> perlversion.txt
          ls -l perlversion.txt

      - name: Cache CPAN modules
        uses: actions/cache@v1
        with:
          path: ~/perl5
          key: ${{ runner.os }}-build-${{ hashFiles('perlversion.txt') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ hashFiles('perlversion.txt') }}

      - name: Install Dynamic Dependencies
        run: |
          # cpanm --notest IO::Socket::SSL
          #cpanm --notest FFI::Platypus::Declare
          #cpanm --notest Task::Biodiverse::NoGUI
          #cpanm Test2::Suite
          #cpanm --notest --installdeps .
          #cpanm --installdeps .
          cpanm --notest Alien::Build
          cpanm --notest Alien::Build::MM
          cpanm --notest Sort::Versions
          cpanm --notest Alien::Build::Plugin::PkgConfig::PPWrapper
          cpanm --notest Alien::geos::af
          cpanm --notest Alien::libtiff
          cpanm --notest Alien::proj
      
      - name: Build and then run tests
        run: |
          perl Makefile.PL
          cpanm --installdeps .
          MAKEFLAGS=-j4 make test
          #prove -l -j4
