name: Windows

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

env:
  AUTOMATED_TESTING: 1

jobs:
  perl:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.38"
          distribution: strawberry
          install-modules-with: cpanm
          install-modules-args: --with-develop --with-configure --verbose

      # Runs a set of commands using the runners shell
      - name: Build
        run: |
          ## echo "ALIEN_GDAL_CONFIG_ARGS=--with-hide_internal_symbols" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          ## $env:ALIEN_GDAL_CONFIG_ARGS = "--with-hide-internal-symbols=yes --without-gnm"
          prove -lv t

#          perl Makefile.PL
#          cpanm --notest --installdeps .
#          gmake
#          gmake test TEST_VERBOSE=1


      #- name: Zip _alien
      #  #if: ${{ failure() }}
      #  if: ${{ always() }}
      #  run: |
      #    pwd
      #    & 7z.exe a _alien.7z _alien
      #
      #- name: Upload artefact
      #  if: ${{ always() }}
      #  uses: actions/upload-artifact@v1
      #  with:
      #    name: _alien.7z
      #    path: ./_alien.7z
