name: Windows

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

env:
  PERL5LIB: c:\cx\lib\perl5
  PERL_LOCAL_LIB_ROOT: c:/cx
  PERL_MB_OPT: --install_base C:/cx
  PERL_MM_OPT: INSTALL_BASE=C:/cx
  ALIEN_BUILD_PRELOAD: Fetch::Cache
  AUTOMATED_TESTING: 1

jobs:
  perl:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Perl
        run: |
          choco install strawberryperl
          echo "C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          ###echo "##[add-path]C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin"
  
      - name: perl -V
        run: perl -V
        
      - name: Prepare for CPAN cache
        run: |
          perl -V > perlversion.txt
          echo '20200611' >> perlversion.txt
          dir perlversion.txt

      - name: Cache CPAN modules
        uses: actions/cache@v1
        with:
          path: c:\cx
          key: ${{ runner.os }}-build-${{ hashFiles('perlversion.txt') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ hashFiles('perlversion.txt') }}

      - name: Prepare for Alien cache
        run: |
          perl -V > aliencache.txt
          echo 'aliens 20200604' >> aliencache.txt
          dir aliencache.txt

      - name: Cache Alien downloads
        uses: actions/cache@v1
        with:
          path: C:\Users\runneradmin\.alienbuild
          key: ${{ runner.os }}-build-${{ hashFiles('aliencache.txt') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ hashFiles('aliencache.txt') }}

      #- name: Install Dependencies
      #  run: curl -sL https://git.io/cpm | perl - install -g --show-build-log-on-failure
  
      - name: Install dependencies 1
        run: |
          cpanm --quiet --notest Alien::Build::Plugin::Fetch::Cache

          #cpanm --notest local::lib
          #eval "$(perl -Mlocal::lib=${PWD}/perl_modules)"
          #cpanm --notest --installdeps .
          #cpanm --quiet --notest Alien::Build
          #cpanm --quiet --notest Alien::Build::MM
          #cpanm --quiet --notest Sort::Versions
          #cpanm --quiet --notest PkgConfig
          #cpanm --quiet --notest Alien::Build::Plugin::Cleanse::BuildDir
          #cpanm --quiet --notest Alien::Build::Plugin::PkgConfig::PPWrapper
          #cpanm --quiet --notest File::Find::Rule
          #cpanm --quiet --notest Env::ShellWords
          #cpanm --quiet --notest FFI::Platypus

      - name: Install dependencies Alien::MSYS
        run: |
          cpanm -v --notest Alien::MSYS

      - name: Install dependencies Alien::sqlite
        run: |
          cpanm -v Alien::sqlite~1.05

      - name: Install dependencies Alien::libtiff
        run: |
          cpanm -v --notest Alien::libtiff

      - name: Install dependencies Alien::proj
        run: |
          #perl -E"eval qq{require Alien::proj} || system (qw {cpanm -v --notest https://github.com/shawnlaffan/perl-alien-proj.git})"
          cpanm -v --notest Alien::proj~1.10

      - name: Install dependencies Alien::geos::af
        run: |
          cpanm -v Alien::geos::af

      - name: Install dependencies for Alien::gdal
        run: |
          cpanm --notest --installdeps Alien::gdal
  
      # Runs a set of commands using the runners shell
      - name: Build
        run: |
          ## echo "ALIEN_GDAL_CONFIG_ARGS=--with-hide_internal_symbols" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          ## $env:ALIEN_GDAL_CONFIG_ARGS = "--with-hide-internal-symbols=yes --without-gnm"
          perl Makefile.PL
          cpanm --notest --installdeps .
          gmake
          gmake test TEST_VERBOSE=1

      #- name: Zip _alien
      #  #if: ${{ failure() }}
      #  if: ${{ always() }}
      #  run: |
      #    pwd
      #    & 7z.exe a _alien.7z _alien
      #    
      #- name: Upload artefact
      #  if: ${{ always() }}
      #  uses: actions/upload-artifact@v1
      #  with:
      #    name: _alien.7z
      #    path: ./_alien.7z
